version: "2"

run:
  go: '1.24'
  timeout: 5m

linters-settings:
  dupl:
    threshold: 100
  funlen:
    lines: 100
    statements: 50
  goconst:
    min-len: 2
    min-occurrences: 3
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  gocyclo:
    min-complexity: 15
  goimports:
    local-prefixes: mermaid-icepanel
  gomnd:
    settings:
      mnd:
        checks: argument,case,condition,return
  govet:
    check-shadowing: true
  lll:
    line-length: 120
  misspell:
    locale: US
  staticcheck:
    checks: ["all"]

formatters:
  enable:
    - gci
    - gofmt
    - goimports

linters:
  disable-all: true
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - contextcheck
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - forbidigo
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - godot
    - goheader
    - gomodguard
    - goprintffuncname
    - gosec
    - govet
    - importas
    - ineffassign
    - lll
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - nosprintfhostport
    - predeclared
    - promlinter
    - revive
    - staticcheck
    - testableexamples
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - wastedassign
    - whitespace

issues:
  # Maximum issues count per one linter (set to 0 to disable)
  max-issues-per-linter: 0
  # Maximum count of issues with the same text
  max-same-issues: 0
  # Show only new issues: only issues that did not exist before this CI build
  new: false

# Output configuration options
output:
  # Format: colored-line-number|line-number|json|tab|checkstyle|code-climate|junit-xml|github-actions
  format: colored-line-number
  # Print lines of code with issue.
  print-issued-lines: true
  # Print linter name in the end of issue text.
  print-linter-name: true 
